### PR TITLE
fix:Added links to the README file

### PR DESCRIPTION
**Pull request by ShaikMoAbdullah**
- [x] Added links to your Linkedin and Twitter profile. Did not find your Discord profile. 
- Thanks for keeping your username in there to give me my first open-source contribution
- Thanks to [Open Source project SHOUTOUTS and reviews!](https://youtu.be/afo0E5RrJYA) by Eddie Hub and Kunal Kushwaha

### CODE REVIEW

**Comment by 0xk4b1r** [comment]
Hey, thanks for contributing and thanks the your time.
 
1. Links are not working, will not maybe under list tags. 
image

and they misunderstood that: those were not profile links, those were for mentioning me on socials, like while twitting or while messaging on discord @kabir0x23 finding me will become easy.

3. I already have changed below things before your pull request: 
image
image

**Comment by 0xk4b1r** [comment]
> * [x]  Added links to your Linkedin and Twitter profile. Did not find your Discord profile.
> 
>     * Thanks for keeping your username in there to give me my first open-source contribution
> 
>     * Thanks to (Open Source project SHOUTOUTS and reviews!)[https://youtu.be/afo0E5RrJYA] by Eddie Hub and Kunal Kushwaha

I am working on some Open source projects, after they got ready, will let you know.

**Comment by 0xk4b1r** [comment]
Hey, I want to give you one tip.
Always create issues first and explain well.
when your pull request is ready, must tag the issue number in the pull request like fixes or closes #1 like that
@ShaikMohammadAbdullah

**Comment by 0xk4b1r** [comment]
in this project's readme, there is a spelling mistake. 
must give a look, i will review and merge it soon
https://github.com/cryptoverseWeb3/Cryptoverse

**Comment by ShaikMoAbdullah** [comment]
Hey @kabir0x23. Thanks for taking time out and giving me that tip. I will keep that in mind.

**Comment by 0xk4b1r** [comment]
And we are closing this PR.
Good luck for your open source journey 🚀

**Pull request closed without merging**
